# Copyright (c) 2021 University System of Georgia and jupyterlab-gt-coar-theme contributors
# Distributed under the terms of the BSD-3-Clause License.

name: jupyterlab-gt-coar-theme

channels:
  - conda-forge
  - nodefaults

dependencies:
  - jupyterlab ==3.*
  - nodejs >=14,<15
  - python >=3.9,<3.10
  - doit
  # qa
  - twine
  - pip
  - black
  - isort
  - flake8
  - pyflakes
  - wheel
