# Copyright (c) 2021 University System of Georgia and jupyterlab-gt-coar-theme contributors
# Distributed under the terms of the BSD-3-Clause License.

name: jupyterlab-gt-coar-theme

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - jupyterlab >=3.0.7
  - nodejs >=14,<15
  - python >=3.9,<3.10
  - doit
  # qa
  - twine
  - pip
  - black
  - isort
  - flake8
  - pyflakes
  - wheel
  # binder biz
  - nbgitpuller
  # demo/integration testing
  - bqplot
  - cookiecutter
  - firefox
  - geckodriver
  - importnb
  - ipydrawio
  - ipyelk
  - ipywidgets
  - jupyter-starters
  - jupyter-videochat
  - jupyterlab_robotmode
  - jupyterlab-lsp
  - jupyterlab-tour
  - pandas
  - python-lsp-server
  - retrolab
  - robotframework-lsp
  - robotframework-seleniumlibrary
  - robotkernel
  - wxyz_datagrid
  - wxyz_dvcs
  - wxyz_json_e
  - wxyz_json_schema_form
  - wxyz_jsonld
  - wxyz_lab
  - wxyz_svg
  - wxyz_tpl_jinja
  - wxyz_yaml
  - xeus-python
