#!/usr/bin/env bash

# Copyright (c) 2021 University System of Georgia and jupyterlab-gt-coar-theme contributors
# Distributed under the terms of the BSD-3-Clause License.
set -eux

doit

mkdir -p ~/.jupyter/lab/
cp -r .binder/user-settings ~/.jupyter/lab/

jupyter labextension uninstall --no-build jupyter-offlinenotebook || echo "ok"
jupyter labextension list

git clone https://github.com/jupyrdf/ipyelk

mkdir examples

pushd ipyelk
    git checkout v1.0.0
    cp -r examples ../examples/ipyelk
popd

git clone https://github.com/bqplot/bqplot

pushd bqplot
    git checkout 0.12.29
    cp -r examples ../examples/bqplot
popd

git clone https://github.com/deathbeds/wxyz

pushd wxyz
    git checkout v0.5.1
    cp -r src/wxyz_notebooks/src/wxyz/notebooks ../examples/wxyz
popd