#!/usr/bin/env bash

# Copyright (c) 2021 University System of Georgia and jupyterlab-gt-coar-theme contributors
# Distributed under the terms of the BSD-3-Clause License.
set -eux

doit

mkdir ~/.jupyter/lab
cp -r .binder/user-settings ~/.jupyter/lab/

jupyter labextension uninstall --no-build jupyter-offlinenotebook || echo "ok"
jupyter labextension list
